config/routes.rb
Rails.application.routes.draw do

  resources :releases

  root 'products#index'
  resources :invoices
  resources :consignments, skip: [:edit, :update, :show, :destroy]
  resources :products
  devise_for :users, skip: [:registrations]

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :purchases

  has_many :products,
           :through => :purchases

  accepts_nested_attributes_for :purchases,
                                :allow_destroy => true
  accepts_nested_attributes_for :products
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "invoice",
               show_as_html: params[:debug] #this is for showing pdf in html for debugging.
      end
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.invoice_number = SecureRandom.hex(4)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:product_id, :customer_name, :customer_phone, :invoice_number, :customer_address,
                                      purchases_attributes: [:product_id, :quantity])
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_confirmation_modal.haml
/ Modal
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title Modal title
      .modal-body
        = form_tag({controller: :releases, :action => 'create'}) do
          .field
            = hidden_field_tag :purchase, purchase
          .field.form-group
            = label_tag "Confirmation Code"
            = text_field_tag :confirmation_code, nil, class: 'form-control'
          .actions
            = submit_tag 'Confirm', class: 'btn btn-lg btn-primary btn-block'

app/views/invoices/_form.html.haml
.container-fluid
  .form-wrapper
    = form_for(@invoice) do |f|
      - if @invoice.errors.any?
        #error_explanation
          %h2
            = pluralize(@invoice.errors.count, "error")
            prohibited this invoice from being saved:
          %ul
            - @invoice.errors.full_messages.each do |message|
              %li= message
      = field_set_tag 'Customer Info' do
        .field.form-group
          = f.label :customer_phone
          = f.number_field :customer_phone, class: "form-control"
        .field.form-group
          = f.label :customer_name
          = f.text_field :customer_name, class: "form-control"
        .field.form-group
          = f.label :customer_address
          = f.text_area :customer_address, class: "form-control"

      = field_set_tag 'Merchandise', id: "invoice-products" do
        %ol
          = f.fields_for :purchases do |purchase|
            = render 'purchase_fields', f: purchase
        = link_to_add_association 'Add Product', f, :purchases, 'data-association-insertion-node' => "#invoice-products ol", 'data-association-insertion-method' => "append", :wrap_object => Proc.new {|purchase| purchase.build_product; purchase }
      .actions
        = f.submit class: "btn btn-lg btn-primary btn-block"

app/views/invoices/_purchase_fields.html.haml
%li.control-group.nested-fields
  .controls
    -#= f.fields_for :product do |p|
    = f.collection_select :product_id, Product.order(:name),:id,:name, include_blank: true

    = f.label :quantity, "Quantity:"
    = f.number_field :quantity, class: "size-5"
    %span
      %i.fa.fa-database Crates

    = link_to_remove_association "remove", f

app/views/invoices/edit.html.haml
%h1 Editing Invoice
= render 'form'
= link_to 'Show', @invoice
|
\#{link_to 'Back', invoices_path}

app/views/invoices/index.html.haml
%h1 Listing Invoices
.table-responsive
  %table#invoices.table.table-bordered.table-hover
    %thead
      %tr
        %th Invoice number
        %th Customer name
        %th Customer phone
        %th Products
        %th Customer address
        %th Actions
    %tbody
      - @invoices.each do |invoice|
        %tr
          %td= link_to invoice.invoice_number.upcase, invoice, title: "View Invoice"
          %td= invoice.customer_name
          %td= invoice.customer_phone
          %td
            - invoice.purchases.each do |purchase|
              = purchase.product.name
          %td= invoice.customer_address
          %td
            = link_to(('<i class="fa fa-pencil-square-o"></i>').html_safe, edit_invoice_path(invoice), title: "Edit Invoice")
            = link_to(('<i class="fa fa-trash"></i>').html_safe, invoice,
            method: :delete, class: "text-danger", title: "Delete Invoice", data: { confirm: 'Are you sure?' })
= link_to(('<i class="fa fa-plus"></i> Create New Invoice').html_safe, new_invoice_path, class: "text-success")

app/views/invoices/new.html.haml
%h1 New Invoice
= render 'form'
= link_to 'Back', invoices_path

app/views/invoices/show.html.haml
.table-responsive.show-tables
  %table.table.table-bordered
    %thead
      %tr
        %th{:colspan => "2"}= "Invoice for: #{@invoice.customer_name}"
    %tbody
      %tr
        %td
          %strong Invoice number:
        %td= @invoice.invoice_number.upcase
      %tr
        %td
          %strong Customer phone:
        %td= @invoice.customer_phone
      %tr
        %td
          %strong Customer address:
        %td= @invoice.customer_address
      %tr
        %td
          %strong Purchases:
        %td
          - @invoice.purchases.each do |purchase|
            .row
              .col-sm-4
                = purchase.product.name
              .col-sm-3
                = purchase.quantity
                %span
                  %i.fa.fa-database Crates
              .col-sm-3
                %i.btn.fa.fa-check-square-o.text-success.modal-check{"data-target" => "#myModal",
                                                                      "data-toggle" => "modal",
                                                                      :type => "button",
                                                                      :id => purchase.id}
            %br
= link_to 'Edit', edit_invoice_path(@invoice)
|
= link_to 'Back', invoices_path


=render 'confirmation_modal', purchase: ''

app/views/invoices/show.pdf.haml
.table-responsive.show-tables
  %table.table.table-bordered
    %thead
      %tr
        %th{:colspan => "2"}= "Invoice for: #{@invoice.customer_name}"
    %tbody
      %tr
        %td
          %strong Invoice number:
        %td= @invoice.invoice_number.upcase
      %tr
        %td
          %strong Customer phone:
        %td= @invoice.customer_phone
      %tr
        %td
          %strong Customer address:
        %td= @invoice.customer_address
      %tr
        %td
          %strong Purchases:
        %td
          - @invoice.purchases.each do |purchase|
            .row
              .col-sm-4
                = purchase.product.name
              .col-sm-3
                = purchase.quantity
                %span
                  %i.fa.fa-database Crates