config/routes.rb
Rails.application.routes.draw do

  resources :releases

  root 'products#index'
  resources :invoices
  resources :consignments, skip: [:edit, :update, :show, :destroy]
  resources :products
  devise_for :users, skip: [:registrations]

end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_action :set_release, only: [:show, :edit, :update, :destroy]

  # GET /releases
  # GET /releases.json
  def index
    @releases = Release.all
  end

  # GET /releases/1
  # GET /releases/1.json
  def show
  end

  # GET /releases/new
  def new
    @release = Release.new
  end

  # GET /releases/1/edit
  def edit
  end

  # POST /releases
  # POST /releases.json
  def create
    @release = Release.new(build_release)

    respond_to do |format|
      if @release.save
        format.html { redirect_to :back, notice: 'Purchase successfully checked off.' }
        format.json { render :show, status: :created, location: @release }
      else
        format.html { redirect_to :back, alert: 'Error occurred, please try again' }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /releases/1
  # PATCH/PUT /releases/1.json
  def update
    respond_to do |format|
      if @release.update(release_params)
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { render :show, status: :ok, location: @release }
      else
        format.html { render :edit }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /releases/1
  # DELETE /releases/1.json
  def destroy
    @release.destroy
    respond_to do |format|
      format.html { redirect_to releases_url, notice: 'Release was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_release
      @release = Release.find(params[:id])
    end

    def build_release
      {
        confirmation_code: params[:confirmation_code],
        user: current_user,
        purchase: Purchase.find(params[:purchase])
      }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def release_params
      params.require(:release).permit(:user_id, :purchase_id, :confirmation_code)
    end
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/releases/_form.html.haml
= form_for @release do |f|
  - if @release.errors.any?
    #error_explanation
      %h2= "#{pluralize(@release.errors.count, "error")} prohibited this release from being saved:"
      %ul
        - @release.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :purchase
    = f.text_field :purchase
  .field
    = f.label :confirmation_code
    = f.text_field :confirmation_code
  .actions
    = f.submit 'Save'

app/views/releases/edit.html.haml
%h1 Editing release

= render 'form'

= link_to 'Show', @release
\|
= link_to 'Back', releases_path

app/views/releases/index.html.haml
%h1 Listing releases
.table-responsive
  %table.table.table-bordered.table-hover#releases
    %thead
      %tr
        %th Buyer
        %th Product
        %th Quantity
        %th Confirmation code
        %th Released By

    %tbody
      - @releases.each do |release|
        %tr
          %td= release.purchase.invoice.customer_name
          %td= release.purchase.product.name
          %td= release.purchase.product.quantity
          %td= release.confirmation_code
          %td= release.user.name
  %br

app/views/releases/new.html.haml
%h1 New release

= render 'form'

= link_to 'Back', releases_path

app/views/releases/show.html.haml
%p
  %b User:
  = @release.user
%p
  %b Purchase:
  = @release.purchase
%p
  %b Confirmation code:
  = @release.confirmation_code

= link_to 'Edit', edit_release_path(@release)
\|
= link_to 'Back', releases_path