config/routes.rb
Rails.application.routes.draw do

  resources :releases

  root 'products#index'
  resources :invoices
  resources :consignments, skip: [:edit, :update, :show, :destroy]
  resources :products
  devise_for :users, skip: [:registrations]

end

app/models/consignment.rb
class Consignment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :product_id, :quantity, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  validate :validate_product_id

  after_commit :keep_product_in_sync, on: :create


  private

  def validate_product_id
    errors.add(:product_id, "we have no such product!") unless Product.exists?(self.product_id)
  end

  def keep_product_in_sync
    product.increment!(:quantity, quantity)
  end
end

app/controllers/consignments_controller.rb
class ConsignmentsController < ApplicationController
  before_action :set_consignment, only: [:show, :edit, :update, :destroy]

  # GET /consignments
  # GET /consignments.json
  def index
    @consignments = Consignment.all
  end

  # GET /consignments/1
  # GET /consignments/1.json
  def show
  end

  # GET /consignments/new
  def new
    @consignment = Consignment.new
  end

  # GET /consignments/1/edit
  def edit
  end

  # POST /consignments
  # POST /consignments.json
  def create
    @consignment = Consignment.new(consignment_params)
    @consignment.user = current_user

    respond_to do |format|
      if @consignment.save
        format.html { redirect_to @consignment, notice: 'Consignment was successfully created.' }
        format.json { render :show, status: :created, location: @consignment }
      else
        format.html { render :new }
        format.json { render json: @consignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consignments/1
  # PATCH/PUT /consignments/1.json
  def update
    respond_to do |format|
      if @consignment.update(consignment_params)
        format.html { redirect_to @consignment, notice: 'Consignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @consignment }
      else
        format.html { render :edit }
        format.json { render json: @consignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consignments/1
  # DELETE /consignments/1.json
  def destroy
    @consignment.destroy
    respond_to do |format|
      format.html { redirect_to consignments_url, notice: 'Consignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consignment
      @consignment = Consignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consignment_params
      params.require(:consignment).permit(:product_id, :quantity, :user_id)
    end
end

app/helpers/consignments_helper.rb
module ConsignmentsHelper
end

app/views/consignments/_form.html.haml
.container-fluid
  .form-wrapper
    = form_for(@consignment) do |f|
      - if @consignment.errors.any?
        #error_explanation
          %h2
            = pluralize(@consignment.errors.count, "error")
            prohibited this consignment from being saved:
          %ul
            - @consignment.errors.full_messages.each do |message|
              %li= message
      .field.form-group
        = f.label :product_id
        = f.collection_select :product_id, Product.order(:name), :id, :name, include_blank: true, class: "form-control"
      .field.form-group
        = f.label :quantity
        = f.number_field :quantity, class: "form-control"
        %span.input-group-addon
          %i.fa.fa-database Crates
      .actions
        = f.submit 'Record Consignment', class: "btn btn-lg btn-primary btn-block", data: { disable_with: "Please wait...", confirm: "Are you sure the Quantity of this Consignment is Correct? You cannot Edit or Delete this consignment once Posted!" }

app/views/consignments/edit.html.haml
%h1 Editing Consignment
= render 'form'
= link_to 'Show', @consignment
|
\#{link_to 'Back', consignments_path}

app/views/consignments/index.html.haml
%h1 Listing Consignments
.table-responsive
  %table#consignments.table.table-bordered.table-hover
    %thead
      %tr
        %th Product
        %th Quantity
        %th User
    %tbody
      - @consignments.each do |consignment|
        %tr
          %td= consignment.product.name
          %td= consignment.quantity
          %td= consignment.user.name
= link_to(('<i class="fa fa-plus"></i> Add New Consignment').html_safe, new_consignment_path, class: "text-success")

app/views/consignments/new.html.haml
%h1 New Consignment
= render 'form'
= link_to 'Back', consignments_path

app/views/consignments/show.html.haml
%p
  %strong Product:
  = @consignment.product
%p
  %strong Quantity:
  = @consignment.quantity
%p
  %strong User:
  = @consignment.user
= link_to 'Edit', edit_consignment_path(@consignment)
|
\#{link_to 'Back', consignments_path}